version: "3.9"

services:
  app:
    env_file:
      - .env
    image: auto-trade:latest
    network_mode: "host"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5371/health-check || exit 1
      interval: 5m
      timeout: 40s
      retries: 3
    restart: always
